import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { SelectBox } from "./SelectBox";
import { ReactTable } from "./ReactTable";
import { Input } from "./Input";
import { Radio } from "./Radio";
import { GoogleMap } from "./GoogleMap";
import { TextArea } from "./TextArea";
export { Img, Text, Heading, Button, SelectBox, ReactTable, Input, Radio, GoogleMap, TextArea };
